# Generated by Django 4.2.3 on 2023-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_booking_no_of_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.SmallIntegerField(),
        ),
    ]
